# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
- name: Setting Fabric-test repository
  hosts: builders
  gather_facts: true
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../../../cello/src/agent/ansible/vars/{{ env }}.yml"
    - "./../../vars/{{ pteenv }}.yml"
  tasks:
    - include: "fabrictestsetup/tasks/{{ mode }}.yml"
  tags: "fabrictestsetup"

- name: Launching PTE container
  hosts: builders
  gather_facts: true
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../../../cello/src/agent/ansible/vars/{{ env }}.yml"
    - "./../../vars/{{ pteenv }}.yml"
  tasks:
    - include: "ptesetup/tasks/{{ mode }}.yml"
  tags: "ptesetup"
