# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
version: 1.0
name: My network
description: Connection Profile used by CI tests for a blockchain network with 4 orderers, 2 peer org with 10 peers each
gopath: GOPATH

# clients
client:
  organization: org1
  connection:
    timeout:
      peer:
        endorser: 300
        eventHub: 600
        eventReg: 300
      orderer: 300

# channels
channels:
  testorgschannel1:
    orderers:
      orderer0
      orderer1
      orderer2
      orderer3
    peers:
      peer0org1examplecom:
      peer1org1examplecom:
      peer0org2examplecom:
      peer1org2examplecom:
    chaincodes: []

#organizations
organizations:
  org1:
    name: PeerOrg1
    mspid: PeerOrg1
    peers:
    - peer0org1examplecom
    - peer1org1examplecom
    - peer2org1examplecom
    - peer3org1examplecom
    - peer4org1examplecom
    - peer5org1examplecom
    - peer6org1examplecom
    - peer7org1examplecom
    - peer8org1examplecom
    - peer9org1examplecom
    certificateAuthorities:
    - ca0
    adminPrivateKey:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    signedCert:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
  org2:
    name: PeerOrg2
    mspid: PeerOrg2
    peers:
    - peer0org2examplecom
    - peer1org2examplecom
    - peer2org2examplecom
    - peer3org2examplecom
    - peer4org2examplecom
    - peer5org2examplecom
    - peer6org2examplecom
    - peer7org2examplecom
    - peer8org2examplecom
    - peer9org2examplecom
    certificateAuthorities:
    - ca1
    adminPrivateKey:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    signedCert:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp

#orderers
orderers:
  orderer0:
    mspid: OrdererOrg
    url: grpcs://localhost:5005
    grpcOptions:
      ssl-target-name-override: orderer0.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp

  orderer1:
    mspid: OrdererOrg
    url: grpcs://localhost:5006
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp

  orderer2:
    mspid: OrdererOrg
    url: grpcs://localhost:5007
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp

  orderer3:
    mspid: OrdererOrg
    url: grpcs://localhost:5008
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    adminPath: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp

# peers
peers:
  peer0org1examplecom:
    url: grpcs://localhost:7061
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer1org1examplecom:
    url: grpcs://localhost:7062
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer2org1examplecom:
    url: grpcs://localhost:7063
    grpcOptions:
      ssl-target-name-override: peer2.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer3org1examplecom:
    url: grpcs://localhost:7064
    grpcOptions:
      ssl-target-name-override: peer3.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer4org1examplecom:
    url: grpcs://localhost:7065
    grpcOptions:
      ssl-target-name-override: peer4.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer5org1examplecom:
    url: grpcs://localhost:7066
    grpcOptions:
      ssl-target-name-override: peer5.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer6org1examplecom:
    url: grpcs://localhost:7067
    grpcOptions:
      ssl-target-name-override: peer6.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer7org1examplecom:
    url: grpcs://localhost:7068
    grpcOptions:
      ssl-target-name-override: peer7.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer8org1examplecom:
    url: grpcs://localhost:7069
    grpcOptions:
      ssl-target-name-override: peer8.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer9org1examplecom:
    url: grpcs://localhost:7070
    grpcOptions:
      ssl-target-name-override: peer9.org1.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer0org2examplecom:
    url: grpcs://localhost:7071
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer1org2examplecom:
    url: grpcs://localhost:7072
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer2org2examplecom:
    url: grpcs://localhost:7073
    grpcOptions:
      ssl-target-name-override: peer2.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer3org2examplecom:
    url: grpcs://localhost:7074
    grpcOptions:
      ssl-target-name-override: peer3.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer4org2examplecom:
    url: grpcs://localhost:7075
    grpcOptions:
      ssl-target-name-override: peer4.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer5org2examplecom:
    url: grpcs://localhost:7076
    grpcOptions:
      ssl-target-name-override: peer5.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer6org2examplecom:
    url: grpcs://localhost:7077
    grpcOptions:
      ssl-target-name-override: peer6.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer7org2examplecom:
    url: grpcs://localhost:7078
    grpcOptions:
      ssl-target-name-override: peer7.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer8org2examplecom:
    url: grpcs://localhost:7079
    grpcOptions:
      ssl-target-name-override: peer8.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer9org2examplecom:
    url: grpcs://localhost:7080
    grpcOptions:
      ssl-target-name-override: peer9.org2.example.com
    tlsCACerts:
      path: src/github.com/hyperledger/fabric-test/fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

# certificateAuthorities
certificateAuthorities:
  ca0:
    url: https://localhost:7054
    caName: ca0
    tlsCACerts:
      path: ../../fabric/internal/cryptogen/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
  ca1:
    url: https://localhost:7055
    caName: ca1
    tlsCACerts:
      path: ../../fabric/internal/cryptogen/crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
